server:
  port: 9102
spring:
  application:
    name: nacos-consumer-openfeign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.102:80



management:
  endpoint:
    web:
      exposure:
        include:'*'
service-url:
  nacos-user-service: http://nacos-provider
