server:
  port: 9102
spring:
  application:
    name: nacos-consumer-openfeign
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.101.160:80
    sentinel:
      transport:
        dashboard: localhost:8080   # 配置sentinel dashboard地址
        port: 8720    # 默认8719端口，假如被占用会自动从8719+1，直到找到未被占用的端口
      web-context-unify: false



management:
  endpoint:
    web:
      exposure:
        include:'*'
service-url:
  nacos-user-service: http://nacos-provider

feign:
  sentinel:
    enabled: true
