server:
  port: 9001
  servlet:
    context-path: /nancy/
spring:
  application:
    name: nacos-provider
  cloud:
    discovery:
      server-addr: 192.168.0.103:80

management:
  endpoint:
    web:
      exposure:
        include: '*'