server:
  port: 9001


spring:
  application:
    name: nacos-provider
  cloud:
    discovery:
      server-addr: localhost:80

    sentinel:
      transport:
        dashboard: localhost:8080   # 配置sentinel dashboard地址
        port: 8720    # 默认8719端口，假如被占用会自动从8719+1，直到找到未被占用的端口

management:
  endpoint:
    web:
      exposure:
        include: '*'