server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.101.197:80
    gateway:
      discovery:
        locator:
          enabled: false # 开启注册中心路由功能
      routes:
        # 配置流量分流权重
        - id: nacos-consumer-router
          uri: lb://nacos-consumer #路由到注册中心，服务为nacos-consumer的服务
          predicates:
            - Path=/testC/** # 路径匹配，则进行路由
            - Weight=group1, 2
          filters:
            - StripPrefix=1 # 截取掉断言路径的第一部分

        - id: nacos-consumer-openfeign
          uri: lb://nacos-consumer-openfeign #路由到注册中心，服务为nacos-consumer的服务
          predicates:
            - Path=/testC/** # 路径匹配，则进行路由
            - Weight=group1, 8
          filters:
            - StripPrefix=1 # 截取掉断言路径的第一部分

        - id: nacos-provider-router
          uri: lb://nacos-provider #路由到注册中心，服务为nacos-provider的服务
          predicates:
            - Path=/nancy/** # 路径匹配，则进行路由
            #- After=2025-03-16T21:40:10.529+08:00[Asia/Shanghai]
            #- Cookie=username,[a-z]+ # 匹配Cookie的key和value（正则表达式）
            #- Header=X-Request-Id,\d+ #表示数字
            #- Host=**.nancy.com #匹配当前的主机地址发出的请求
            #- Method=POST,GET # 匹配GET请求或者POST请求
            #- Query=id,.+ # 匹配请求参数，这里如果需要匹配多个参数，可以写多个Query

          filters:
            - StripPrefix=1 # 截取掉断言路径的第一部分
            - AddRequestHeader=X-Request-red, blue
            - AddRequestParameter=are_you_OK, year
            - AddResponseHeader=X-Response-Red, Blue

        - id: nacos-consumer-router
          uri: lb://nacos-consumer #路由到注册中心，服务为nacos-consumer的服务
          predicates:
            - Path=/testB/** # 路径匹配，则进行路由
          filters:
            - StripPrefix=1 # 截取掉断言路径的第一部分
        - id: nacos-consumer-openfeign
          uri: lb://nacos-consumer-openfeign #路由到注册中心，服务为nacos-consumer的服务
          predicates:
            - Path=/testA/** # 路径匹配，则进行路由
          filters:
            - StripPrefix=1 # 截取掉断言路径的第一部分

management:
  endpoint:
    web:
      exposure:
        include: '*'


