server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103:80
    gateway:
      discovery:
        locator:
          enabled: false # 开启注册中心路由功能
      routes:
        - id: nacos-provider
          uri: lb://nacos-provider #路由到注册中心，服务为nacos-provider的服务
          predicates:
            - Path=/nancy/** # 路径匹配，则进行路由
          filters:
            - StripPrefix=1 # 截取掉断言路径的第一部分
management:
  endpoint:
    web:
      exposure:
        include: '*'


