server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103:80
    gateway:
      discovery:
        locator:
          enabled: true # 开启注册中心路由功能

management:
  endpoint:
    web:
      exposure:
        include: '*'

