server:
  port: 9002


spring:
  application:
    name: nacos-provider
  cloud:
    discovery:
      server-addr: 172.18.101.197:80

management:
  endpoint:
    web:
      exposure:
        include: '*'