server:
  port: 9101
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.101.197:80

    sentinel:
      transport:
        dashboard: localhost:8080   # 配置sentinel dashboard地址
        port: 8720    # 默认8719端口，假如被占用会自动从8719+1，直到找到未被占用的端口
      web-context-unify: false
      datasource: # 配置Sentinel的持久化
        nacos:
          nacos:
            serverAddr: localhost:8848
            groupId: DEFAULT_GROUP
            dataId: order-sentinel.json
            ruleType: flow

management:
  endpoint:
    web:
      exposure:
        include:'*'
service-url:
  nacos-user-service: http://nacos-provider