server:
  port: 9101
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103:80

management:
  endpoint:
    web:
      exposure:
        include:'*'
service-url:
  nacos-user-service: http://nacos-provider